// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgxwYutPjjRKO_IPzo5b8n17hqyPTzRV8',
    appId: '1:609332570174:web:a8641de982673cde8f096f',
    messagingSenderId: '609332570174',
    projectId: 'work-72b4d',
    authDomain: 'work-72b4d.firebaseapp.com',
    storageBucket: 'work-72b4d.firebasestorage.app',
    measurementId: 'G-B2SY16PDSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASiYVPG3bjj3-WR1ZUftg9VEaiwahyufY',
    appId: '1:609332570174:android:d1c509ed95c85a3c8f096f',
    messagingSenderId: '609332570174',
    projectId: 'work-72b4d',
    storageBucket: 'work-72b4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASjT6y5DMaqsRjLMg5DNlXhkR1c506TzI',
    appId: '1:609332570174:ios:d647319f39a033dd8f096f',
    messagingSenderId: '609332570174',
    projectId: 'work-72b4d',
    storageBucket: 'work-72b4d.firebasestorage.app',
    iosBundleId: 'com.example.works',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASjT6y5DMaqsRjLMg5DNlXhkR1c506TzI',
    appId: '1:609332570174:ios:d647319f39a033dd8f096f',
    messagingSenderId: '609332570174',
    projectId: 'work-72b4d',
    storageBucket: 'work-72b4d.firebasestorage.app',
    iosBundleId: 'com.example.works',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgxwYutPjjRKO_IPzo5b8n17hqyPTzRV8',
    appId: '1:609332570174:web:910c4ca814dc45f48f096f',
    messagingSenderId: '609332570174',
    projectId: 'work-72b4d',
    authDomain: 'work-72b4d.firebaseapp.com',
    storageBucket: 'work-72b4d.firebasestorage.app',
    measurementId: 'G-8ZKRYYYRL5',
  );
}
